Dev
5oStudios/prayer-times pull request #79
Opened 2024-07-29 16:00 UTC by faragzz

2024-07-29 18:01 UTC, abdelrahman-essawy commented
@faragzz please Include the purpose of this Pull Request. For example:
- This PR adds the ability to…
- This PR simplifies the display of…
- This PR fixes handling of…

also in the future try to split features/fixes into different PRs, it's hard to review ```+12,263 −9,566``` lines on one go.

2024-07-29 18:03 UTC, abdelrahman-essawy commented on apps/frontend/app/[lang]/page.tsx
> +      dispatch(setEnableCountDown(false));
no need for this, you can set it up as the `initalState` in the `settings` slice.

2024-07-29 18:07 UTC, abdelrahman-essawy commented on apps/frontend/app/[lang]/page.tsx
> +        onClick={() => window.location.reload()}
this must be fixed, as no state should depend on native window reload in React App.

think of it as:
using `location.reload()` is like `Windows OS` forcing you to restart the computer in order to proceed.

2024-07-29 18:08 UTC, abdelrahman-essawy commented on apps/frontend/assets/css/global.css
you should split css props into `*.module.css` files. using `global.css` will surely cause css leaking in the near future.

2024-07-29 18:12 UTC, abdelrahman-essawy commented on apps/frontend/components/settings/displayScreen/adjustTimes.tsx
> +    dispatch(setAdjustPrayTimes(updatedTimePeriod));
this is hard to read and should be simplified.

2024-07-29 18:13 UTC, abdelrahman-essawy commented on apps/frontend/components/settings/displayScreen/adjustTimes.tsx
> +        defaultValue={timePeriod[index]}
I would recommend using `id`, as `index` can and will change.

2024-07-29 18:14 UTC, abdelrahman-essawy commented on apps/frontend/components/settings/displayScreen/themes.tsx
> +    dispatch(setHideScreen(!hadithScreen));
I would recommend changing the name to `toggleHideScreen` to be less confusing.

2024-07-29 18:16 UTC, abdelrahman-essawy commented on apps/frontend/components/settings/displayScreen/timer.tsx
>          const timer = setInterval(() => {
clear this timer on component `dismount`

see: https://stackoverflow.com/a/67072456/22140195

2024-07-29 18:19 UTC, abdelrahman-essawy requested changes
`12 / 26 files viewed`, please start addressing the requested changes, until reviewing the remaining files.

2024-07-30 09:52 UTC, faragzz commented on apps/frontend/app/[lang]/page.tsx
> +      dispatch(setEnableCountDown(false));
I need to add this because if someone reloads the screen when for example a show Azan screen is enabled I want it to return to disabled again . I already disabled those features at init in the redux

2024-07-30 09:52 UTC, faragzz commented on apps/frontend/app/[lang]/page.tsx
> +        onClick={() => window.location.reload()}
this feature was requested

2024-07-30 11:00 UTC, abdelrahman-essawy approved these changes
TODO: refactor `settings slice` to reduce selectors and setters.

2024-07-30 11:06 UTC, merged